name: Build Compositor
on:
  workflow_dispatch: # 支持手动点击 Run workflow 触发

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Compositor
        run: |
          xcodebuild -project Compositor.xcodeproj -scheme Compositor -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Zip App
        run: |
          cd build/Release
          zip -r Compositor.zip Compositor.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compositor-macos14-build
          path: build/Release/Compositor.zip
